<a href="https://colab.research.google.com/github/sindhuudivyapriya1998-collab/Cross-Market-Analysis/blob/main/divi_project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cross Market Analysis

---

# **crypto currency**

In [64]:
import requests
import time

crypto_data =[]

for page in range(1,8):
   url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page={page}&sparkline=False"

   response = requests.get(url)

   if response.status_code == 200:
     data = response.json()
     crypto_data.extend(data)
     time.sleep(20)

In [65]:
len(crypto_data)

1000

In [69]:
import pandas as pd
df = pd.DataFrame(crypto_data)
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,5.668437e+06,113683469483917,1,113683469483917,3.156319e+12,5.728486e+06,...,2.004873e+07,2.100000e+07,1.118701e+07,-49.33020,2025-10-06T18:57:42.558Z,3993.420000,1.418444e+05,2013-07-05T00:00:00.000Z,None,2026-06-27T05:32:18.089Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1.486210e+05,17943851404529,2,17943851404529,1.101571e+12,1.495450e+05,...,1.206835e+08,NaN,4.319460e+05,-65.59265,2025-08-24T19:21:03.333Z,28.130000,5.282132e+05,2015-10-20T00:00:00.000Z,"{'times': 34.04730068525593, 'currency': 'btc'...",2026-06-27T05:32:18.603Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,9.422000e+01,17557955064744,3,18073092330965,5.021620e+12,9.456000e+01,...,1.918024e+11,NaN,1.055200e+02,-10.70423,2025-01-25T16:51:57.989Z,36.860000,1.556289e+02,2015-03-02T00:00:00.000Z,None,2026-06-27T05:32:18.879Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,5.316400e+04,7166757827188,4,7166757827188,8.275596e+10,5.380200e+04,...,1.347829e+08,2.000000e+08,1.214220e+05,-56.21539,2025-10-13T08:41:24.131Z,2.580000,2.056749e+06,2017-10-19T00:00:00.000Z,None,2026-06-27T05:32:17.997Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,9.434000e+01,6961364951528,5,6962412106383,1.406526e+12,9.466000e+01,...,7.379803e+10,NaN,9.698000e+01,-2.72596,2026-05-20T14:19:58.071Z,65.310000,4.444812e+01,2021-05-19T13:14:05.611Z,None,2026-06-27T05:32:18.442Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,boundless,zkc,Boundless,https://coin-images.coingecko.com/coins/images...,4.180000e+00,1217239570,996,4418428355,3.108429e+08,4.250000e+00,...,1.054991e+09,NaN,1.567600e+02,-97.32018,2025-09-15T13:59:08.030Z,4.020000,4.614850e+00,2026-06-26T02:25:56.377Z,None,2026-06-27T05:33:11.558Z
996,taiko,taiko,Taiko,https://coin-images.coingecko.com/coins/images...,6.200000e+00,1212686210,997,6200202923,2.392699e+08,6.340000e+00,...,1.000000e+09,1.000000e+09,3.171900e+02,-98.03725,2024-06-05T13:01:31.342Z,5.700000,9.288930e+00,2026-06-25T15:20:34.803Z,None,2026-06-27T05:33:07.077Z
997,avalaunch,xava,Avalaunch,https://coin-images.coingecko.com/coins/images...,2.835000e+01,1205041928,998,2834965101,1.767608e+07,2.850000e+01,...,1.000000e+08,1.000000e+08,1.509300e+03,-98.12122,2021-12-03T14:12:24.965Z,9.760000,1.905106e+02,2026-02-08T11:57:12.441Z,None,2026-06-27T05:33:18.619Z
998,proton-loan,loan,Loan Protocol,https://coin-images.coingecko.com/coins/images...,3.567160e-02,1200308631,1003,4029487328,1.026429e+07,3.708476e-02,...,1.129606e+11,NaN,2.445720e-01,-85.23009,2025-08-09T21:02:53.778Z,0.000340,1.053209e+04,2023-09-03T12:29:45.262Z,None,2026-06-27T05:33:04.241Z
999,diam,diam,DIAM,https://coin-images.coingecko.com/coins/images...,5.933620e-01,1197380315,1000,3205020248,2.662849e+07,5.936820e-01,...,5.401462e+09,1.000000e+10,2.870000e+00,-79.36133,2025-02-13T03:10:08.189Z,0.585706,1.229220e+00,2025-02-18T10:01:49.443Z,None,2026-06-27T05:33:09.531Z

In [70]:
df.to_csv("crypto_data.csv",index=False)

In [71]:
df['last_updated'] = pd.to_datetime(df['last_updated']).dt.date
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,5.668437e+06,113683469483917,1,113683469483917,3.156319e+12,5.728486e+06,...,2.004873e+07,2.100000e+07,1.118701e+07,-49.33020,2025-10-06T18:57:42.558Z,3993.420000,1.418444e+05,2013-07-05T00:00:00.000Z,None,2026-06-27
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1.486210e+05,17943851404529,2,17943851404529,1.101571e+12,1.495450e+05,...,1.206835e+08,NaN,4.319460e+05,-65.59265,2025-08-24T19:21:03.333Z,28.130000,5.282132e+05,2015-10-20T00:00:00.000Z,"{'times': 34.04730068525593, 'currency': 'btc'...",2026-06-27
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,9.422000e+01,17557955064744,3,18073092330965,5.021620e+12,9.456000e+01,...,1.918024e+11,NaN,1.055200e+02,-10.70423,2025-01-25T16:51:57.989Z,36.860000,1.556289e+02,2015-03-02T00:00:00.000Z,None,2026-06-27
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,5.316400e+04,7166757827188,4,7166757827188,8.275596e+10,5.380200e+04,...,1.347829e+08,2.000000e+08,1.214220e+05,-56.21539,2025-10-13T08:41:24.131Z,2.580000,2.056749e+06,2017-10-19T00:00:00.000Z,None,2026-06-27
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,9.434000e+01,6961364951528,5,6962412106383,1.406526e+12,9.466000e+01,...,7.379803e+10,NaN,9.698000e+01,-2.72596,2026-05-20T14:19:58.071Z,65.310000,4.444812e+01,2021-05-19T13:14:05.611Z,None,2026-06-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,boundless,zkc,Boundless,https://coin-images.coingecko.com/coins/images...,4.180000e+00,1217239570,996,4418428355,3.108429e+08,4.250000e+00,...,1.054991e+09,NaN,1.567600e+02,-97.32018,2025-09-15T13:59:08.030Z,4.020000,4.614850e+00,2026-06-26T02:25:56.377Z,None,2026-06-27
996,taiko,taiko,Taiko,https://coin-images.coingecko.com/coins/images...,6.200000e+00,1212686210,997,6200202923,2.392699e+08,6.340000e+00,...,1.000000e+09,1.000000e+09,3.171900e+02,-98.03725,2024-06-05T13:01:31.342Z,5.700000,9.288930e+00,2026-06-25T15:20:34.803Z,None,2026-06-27
997,avalaunch,xava,Avalaunch,https://coin-images.coingecko.com/coins/images...,2.835000e+01,1205041928,998,2834965101,1.767608e+07,2.850000e+01,...,1.000000e+08,1.000000e+08,1.509300e+03,-98.12122,2021-12-03T14:12:24.965Z,9.760000,1.905106e+02,2026-02-08T11:57:12.441Z,None,2026-06-27
998,proton-loan,loan,Loan Protocol,https://coin-images.coingecko.com/coins/images...,3.567160e-02,1200308631,1003,4029487328,1.026429e+07,3.708476e-02,...,1.129606e+11,NaN,2.445720e-01,-85.23009,2025-08-09T21:02:53.778Z,0.000340,1.053209e+04,2023-09-03T12:29:45.262Z,None,2026-06-27
999,diam,diam,DIAM,https://coin-images.coingecko.com/coins/images...,5.933620e-01,1197380315,1000,3205020248,2.662849e+07,5.936820e-01,...,5.401462e+09,1.000000e+10,2.870000e+00,-79.36133,2025-02-13T03:10:08.189Z,0.585706,1.229220e+00,2025-02-18T10:01:49.443Z,None,2026-06-27

In [72]:
df = df[['id','symbol','name','current_price','market_cap','market_cap_rank','total_volume','circulating_supply','total_supply','ath','atl','last_updated']]
df

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,5.668437e+06,113683469483917,1,3.156319e+12,2.004873e+07,2.004873e+07,1.118701e+07,3993.420000,2026-06-27
1,ethereum,eth,Ethereum,1.486210e+05,17943851404529,2,1.101571e+12,1.206835e+08,1.206835e+08,4.319460e+05,28.130000,2026-06-27
2,tether,usdt,Tether,9.422000e+01,17557955064744,3,5.021620e+12,1.863354e+11,1.918024e+11,1.055200e+02,36.860000,2026-06-27
3,binancecoin,bnb,BNB,5.316400e+04,7166757827188,4,8.275596e+10,1.347829e+08,1.347829e+08,1.214220e+05,2.580000,2026-06-27
4,usd-coin,usdc,USDC,9.434000e+01,6961364951528,5,1.406526e+12,7.378693e+10,7.379803e+10,9.698000e+01,65.310000,2026-06-27
...,...,...,...,...,...,...,...,...,...,...,...,...
995,boundless,zkc,Boundless,4.180000e+00,1217239570,996,3.108429e+08,2.906410e+08,1.054991e+09,1.567600e+02,4.020000,2026-06-27
996,taiko,taiko,Taiko,6.200000e+00,1212686210,997,2.392699e+08,1.955881e+08,1.000000e+09,3.171900e+02,5.700000,2026-06-27
997,avalaunch,xava,Avalaunch,2.835000e+01,1205041928,998,1.767608e+07,4.250641e+07,1.000000e+08,1.509300e+03,9.760000,2026-06-27
998,proton-loan,loan,Loan Protocol,3.567160e-02,1200308631,1003,1.026429e+07,3.364886e+10,1.129606e+11,2.445720e-01,0.000340,2026-06-27
999,diam,diam,DIAM,5.933620e-01,1197380315,1000,2.662849e+07,2.017961e+09,5.401462e+09,2.870000e+00,0.585706,2026-06-27

# **Coin Records**

In [45]:
import requests
import pandas as pd
import time

price_records =[]
for coin_id in ["bitcoin","ethereum","tether"]:
  url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=inr&days=365"

  response = requests.get(url)
  if response.status_code == 200:
    coin = response.json()
    for ts, price in coin.get("prices",[]):
      price_records.append({"coin_id":coin_id,"date":ts,"price_inr":price})
price_records
time.sleep(10)

In [46]:
len(price_records)

1098

In [47]:
import pandas as pd
df_coin = pd.DataFrame(price_records)
df_coin

      coin_id           date     price_inr
0     bitcoin  1751068800000  9.156218e+06
1     bitcoin  1751155200000  9.177823e+06
2     bitcoin  1751241600000  9.263092e+06
3     bitcoin  1751328000000  9.181709e+06
4     bitcoin  1751414400000  9.054321e+06
...       ...            ...           ...
1093   tether  1782259200000  9.506601e+01
1094   tether  1782345600000  9.429434e+01
1095   tether  1782432000000  9.426604e+01
1096   tether  1782518400000  9.419834e+01
1097   tether  1782537609000  9.422330e+01

[1098 rows x 3 columns]

In [50]:
df_coin.to_csv("top3_data.csv",index=False)

In [51]:
from google.colab import files
files.download("top3_data.csv")

In [48]:
df_coin["date"]= pd.to_datetime(df_coin["date"], unit ="ms").dt.date
df_coin

      coin_id        date     price_inr
0     bitcoin  2025-06-28  9.156218e+06
1     bitcoin  2025-06-29  9.177823e+06
2     bitcoin  2025-06-30  9.263092e+06
3     bitcoin  2025-07-01  9.181709e+06
4     bitcoin  2025-07-02  9.054321e+06
...       ...         ...           ...
1093   tether  2026-06-24  9.506601e+01
1094   tether  2026-06-25  9.429434e+01
1095   tether  2026-06-26  9.426604e+01
1096   tether  2026-06-27  9.419834e+01
1097   tether  2026-06-27  9.422330e+01

[1098 rows x 3 columns]

# **oil** **price**

In [52]:
import pandas as pd
df_oil = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
df_oil =df_oil.rename(columns={"Date":"date","Price":"price_inr"})
df_oil

             date  price_inr
0      1986-01-02      25.56
1      1986-01-03      26.00
2      1986-01-06      26.53
3      1986-01-07      25.85
4      1986-01-08      25.87
...           ...        ...
10181  2026-06-15      84.65
10182  2026-06-16      79.80
10183  2026-06-17      80.65
10184  2026-06-18      80.35
10185  2026-06-22      78.94

[10186 rows x 2 columns]

In [53]:
df_oil.to_csv("oil_data.csv",index=False)

In [54]:
from google.colab import files
files.download("oil_data.csv")

In [18]:
df_oil["date"] = pd.to_datetime(df_oil["date"])
df_oil

            date  price_inr
0     1986-01-02      25.56
1     1986-01-03      26.00
2     1986-01-06      26.53
3     1986-01-07      25.85
4     1986-01-08      25.87
...          ...        ...
10181 2026-06-15      84.65
10182 2026-06-16      79.80
10183 2026-06-17      80.65
10184 2026-06-18      80.35
10185 2026-06-22      78.94

[10186 rows x 2 columns]

In [19]:
df_oil =df_oil[df_oil["date"] > "2020-01-01"]
df_oil

            date  price_inr
8569  2020-01-02      61.17
8570  2020-01-03      63.00
8571  2020-01-06      63.27
8572  2020-01-07      62.70
8573  2020-01-08      59.65
...          ...        ...
10181 2026-06-15      84.65
10182 2026-06-16      79.80
10183 2026-06-17      80.65
10184 2026-06-18      80.35
10185 2026-06-22      78.94

[1617 rows x 2 columns]

#**Stocks Records**

In [55]:
import yfinance as yf
import pandas as pd

tickers = ["^GSPC","^IXIC","^NSEI"]
start_date = "2020-01-01"
end_date = "2026-03-09"

stocks = yf.download(tickers, start = start_date, end= end_date, group_by="tickers")
stocks.head()

/tmp/ipykernel_2522/612559452.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks = yf.download(tickers, start = start_date, end= end_date, group_by="tickers")
[*********************100%***********************]  3 of 3 completed

Ticker            ^GSPC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

Ticker             ^NSEI                                                      \
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

Ticker            ^IXIC
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

In [21]:
df_list =[]
for ticker in tickers:
   text=stocks[ticker].reset_index()
   text['Ticker'] = ticker
   df_list.append(text)
df_all = pd.concat(df_list,ignore_index=True)
df_all

Price,Date,Open,High,Low,Close,Volume,Ticker,Adj Close
0,2020-01-01,NaN,NaN,NaN,NaN,NaN,^GSPC,NaN
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC,NaN
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC,NaN
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC,NaN
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC,NaN
...,...,...,...,...,...,...,...,...
4804,2026-03-02,24659.250000,24989.349609,24603.500000,24865.699219,5.192000e+05,^NSEI,NaN
4805,2026-03-03,NaN,NaN,NaN,NaN,NaN,^NSEI,NaN
4806,2026-03-04,24388.800781,24602.449219,24305.400391,24480.500000,5.990000e+05,^NSEI,NaN
4807,2026-03-05,24615.949219,24854.199219,24529.400391,24765.900391,5.043000e+05,^NSEI,NaN
4808,2026-03-06,24656.400391,24700.900391,24415.750000,24450.449219,4.334000e+05,^NSEI,NaN

In [25]:
df_stocks1 = df_all[df_all['Ticker'] == '^NSEI'].reset_index(drop=True)
df_stocks1

Price,Date,Open,High,Low,Close,Volume,Ticker,Adj Close
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0,^NSEI,NaN
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0,^NSEI,NaN
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0,^NSEI,NaN
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0,^NSEI,NaN
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0,^NSEI,NaN
...,...,...,...,...,...,...,...,...
1598,2026-03-02,24659.250000,24989.349609,24603.500000,24865.699219,519200.0,^NSEI,NaN
1599,2026-03-03,NaN,NaN,NaN,NaN,NaN,^NSEI,NaN
1600,2026-03-04,24388.800781,24602.449219,24305.400391,24480.500000,599000.0,^NSEI,NaN
1601,2026-03-05,24615.949219,24854.199219,24529.400391,24765.900391,504300.0,^NSEI,NaN
1602,2026-03-06,24656.400391,24700.900391,24415.750000,24450.449219,433400.0,^NSEI,NaN

In [22]:
df_stocks2 = df_all[df_all['Ticker'] == '^GSPC'].reset_index(drop=True)
df_stocks2

Price,Date,Open,High,Low,Close,Volume,Ticker,Adj Close
0,2020-01-01,NaN,NaN,NaN,NaN,NaN,^GSPC,NaN
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC,NaN
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC,NaN
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC,NaN
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC,NaN
...,...,...,...,...,...,...,...,...
1598,2026-03-02,6824.359863,6901.009766,6796.850098,6881.620117,6.079080e+09,^GSPC,NaN
1599,2026-03-03,6800.259766,6840.049805,6710.419922,6816.629883,6.442080e+09,^GSPC,NaN
1600,2026-03-04,6831.689941,6885.939941,6811.640137,6869.500000,5.252170e+09,^GSPC,NaN
1601,2026-03-05,6851.080078,6870.430176,6770.779785,6830.709961,5.989300e+09,^GSPC,NaN
1602,2026-03-06,6769.029785,6773.419922,6711.560059,6740.020020,5.793120e+09,^GSPC,NaN

In [23]:
df_stocks3 = df_all[df_all['Ticker'] == '^IXIC'].reset_index(drop=True)
df_stocks3

Price       Date  Open  High  Low  Close  Volume Ticker  Adj Close
0     2020-01-01   NaN   NaN  NaN    NaN     NaN  ^IXIC        NaN
1     2020-01-02   NaN   NaN  NaN    NaN     NaN  ^IXIC        NaN
2     2020-01-03   NaN   NaN  NaN    NaN     NaN  ^IXIC        NaN
3     2020-01-06   NaN   NaN  NaN    NaN     NaN  ^IXIC        NaN
4     2020-01-07   NaN   NaN  NaN    NaN     NaN  ^IXIC        NaN
...          ...   ...   ...  ...    ...     ...    ...        ...
1598  2026-03-02   NaN   NaN  NaN    NaN     NaN  ^IXIC        NaN
1599  2026-03-03   NaN   NaN  NaN    NaN     NaN  ^IXIC        NaN
1600  2026-03-04   NaN   NaN  NaN    NaN     NaN  ^IXIC        NaN
1601  2026-03-05   NaN   NaN  NaN    NaN     NaN  ^IXIC        NaN
1602  2026-03-06   NaN   NaN  NaN    NaN     NaN  ^IXIC        NaN

[1603 rows x 8 columns]

In [26]:
df_stocks = pd.concat([df_stocks1,df_stocks2,df_stocks3])
df_stocks

Price,Date,Open,High,Low,Close,Volume,Ticker,Adj Close
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0,^NSEI,NaN
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0,^NSEI,NaN
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0,^NSEI,NaN
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0,^NSEI,NaN
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0,^NSEI,NaN
...,...,...,...,...,...,...,...,...
1598,2026-03-02,NaN,NaN,NaN,NaN,NaN,^IXIC,NaN
1599,2026-03-03,NaN,NaN,NaN,NaN,NaN,^IXIC,NaN
1600,2026-03-04,NaN,NaN,NaN,NaN,NaN,^IXIC,NaN
1601,2026-03-05,NaN,NaN,NaN,NaN,NaN,^IXIC,NaN
1602,2026-03-06,NaN,NaN,NaN,NaN,NaN,^IXIC,NaN

In [56]:
df_stocks.to_csv("stocks_data.csv")

In [57]:
from google.colab import files
files.download("stocks_data.csv")

# SQL Connection

In [78]:
from google.colab import files
files.download("crypto.db")

In [75]:
import sqlite3
connection = sqlite3.connect("crypto.db")
cursor = connection.cursor()
print("connected")

connected

In [76]:
df_oil.to_sql("oil_record",if_exists="replace",con = connection,index=False)

10186

In [61]:
df_coin.to_sql("coin_record",if_exists="replace",con = connection,index=False )

1098

In [77]:
df.to_sql("crypto_record",if_exists="replace",con = connection,index=False )

1000

In [36]:
df_stocks.to_sql("stocks_record",if_exists="replace",con = connection,index=False )

4809

In [ ]:
pd.read_sql("select * from oil_record",connection)

                     date  price_inr
0     2020-01-02 00:00:00      61.17
1     2020-01-03 00:00:00      63.00
2     2020-01-06 00:00:00      63.27
3     2020-01-07 00:00:00      62.70
4     2020-01-08 00:00:00      59.65
...                   ...        ...
1612  2026-06-15 00:00:00      84.65
1613  2026-06-16 00:00:00      79.80
1614  2026-06-17 00:00:00      80.65
1615  2026-06-18 00:00:00      80.35
1616  2026-06-22 00:00:00      78.94

[1617 rows x 2 columns]

In [ ]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';",connection)

            name
0  stocks_record
1  crypto_record
2     oil_record
3    coin_record

In [ ]:
pd.read_sql("SELECT * FROM crypto_record LIMIT 5",connection)

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,6057345.00,121425058802920,1,1.629302e+12,2.004592e+07,2.004592e+07,11187013.00,3993.42,2026-06-21
1,ethereum,eth,Ethereum,162936.00,19663755377635,2,9.291940e+11,1.206839e+08,1.206839e+08,431946.00,28.13,2026-06-21
2,tether,usdt,Tether,94.42,17602479444107,3,3.097083e+12,1.864367e+11,1.919036e+11,105.52,36.86,2026-06-21
3,binancecoin,bnb,BNB,55518.00,7482911438922,4,4.536807e+10,1.347834e+08,1.347834e+08,121422.00,2.58,2026-06-21
4,usd-coin,usdc,USDC,94.51,7073328896780,5,5.721472e+11,7.484294e+10,7.484325e+10,96.98,65.31,2026-06-21

In [79]:
query1 = pd.read_sql("SELECT * FROM crypto_record ORDER BY market_cap DESC limit 3",connection)
query1

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,5668437.00,113683469483917,1,3.156319e+12,2.004873e+07,2.004873e+07,11187013.00,3993.42,2026-06-27
1,ethereum,eth,Ethereum,148621.00,17943851404529,2,1.101571e+12,1.206835e+08,1.206835e+08,431946.00,28.13,2026-06-27
2,tether,usdt,Tether,94.22,17557955064744,3,5.021620e+12,1.863354e+11,1.918024e+11,105.52,36.86,2026-06-27

In [80]:
query2 = pd.read_sql("SELECT * FROM crypto_record WHERE circulating_supply > 0.9 * total_supply",connection )
query2

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,5.668437e+06,113683469483917,1,3.156319e+12,2.004873e+07,2.004873e+07,11187013.00,3993.420000,2026-06-27
1,ethereum,eth,Ethereum,1.486210e+05,17943851404529,2,1.101571e+12,1.206835e+08,1.206835e+08,431946.00,28.130000,2026-06-27
2,tether,usdt,Tether,9.422000e+01,17557955064744,3,5.021620e+12,1.863354e+11,1.918024e+11,105.52,36.860000,2026-06-27
3,binancecoin,bnb,BNB,5.316400e+04,7166757827188,4,8.275596e+10,1.347829e+08,1.347829e+08,121422.00,2.580000,2026-06-27
4,usd-coin,usdc,USDC,9.434000e+01,6961364951528,5,1.406526e+12,7.378693e+10,7.379803e+10,96.98,65.310000,2026-06-27
...,...,...,...,...,...,...,...,...,...,...,...,...
536,heima,hei,Heima,1.283000e+01,1253886472,987,5.758522e+09,9.775916e+07,1.000000e+08,108.45,4.220000,2026-06-27
537,sofi-technologies-ondo-tokenized-stock,sofion,SoFi Technologies (Ondo Tokenized Stock),1.662780e+03,1251045088,986,6.672097e+06,7.523810e+05,7.523810e+05,2461.86,1392.250000,2026-06-27
538,saucerswap,sauce,SaucerSwap,1.360000e+00,1235674640,990,4.820114e+06,9.068109e+08,1.000000e+09,19.36,0.822745,2026-06-27
539,farcana,far,FAR Labs,2.519220e-01,1229247982,991,1.433566e+07,4.879471e+09,5.000000e+09,17.88,0.013396,2026-06-27
540,apertum,aptm,Apertum,1.164000e+01,1221918475,994,6.590899e+07,1.050010e+08,1.099246e+08,177.67,11.210000,2026-06-27

In [82]:
query3 = pd.read_sql("select * FROM crypto_record WHERE current_price >= ath * 0.90",connection)
query3

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,usd-coin,usdc,USDC,94.34,6961364951528,5,1.406526e+12,7.378693e+10,7.379803e+10,96.98,65.310000,2026-06-27
1,figure-heloc,figr_heloc,Figure Heloc,97.01,1869867763320,9,3.334725e+10,1.927546e+10,1.927546e+10,100.40,13.780000,2026-06-27
2,rain,rain,Rain,1.48,978646642450,12,3.727387e+09,6.618133e+11,1.149854e+12,1.53,0.196087,2026-06-27
3,usd1-wlfi,usd1,USD1,94.29,441005539723,23,1.125006e+11,4.677020e+09,4.677020e+09,96.97,83.750000,2026-06-27
4,dai,dai,Dai,94.34,436598966085,24,2.120118e+10,4.627992e+09,4.627992e+09,96.98,64.850000,2026-06-27
...,...,...,...,...,...,...,...,...,...,...,...,...
144,chinese-oil-asset-reserve,coar,Chinese Oil Asset Reserve,1.50,1501552797,921,0.000000e+00,9.999673e+08,9.999673e+08,1.56,0.540673,2026-06-27
145,celo-dollar,usdm,Mento Dollar,94.34,1452805506,928,6.996959e+07,1.539972e+07,1.539972e+07,97.99,44.270000,2026-06-27
146,ishares-core-us-aggregate-bond-etf-ondo-tokeni...,aggon,iShares Core US Aggregate Bond ETF (Ondo Token...,9638.43,1365213297,953,1.578939e+07,1.416427e+05,1.416427e+05,9885.57,8670.460000,2026-06-27
147,esui-dollar,suiusde,eSui Dollar,94.33,1269811889,979,2.658433e+06,1.346075e+07,1.346075e+07,97.48,90.440000,2026-06-27
148,pathusd,pathusd,pathUSD,94.33,1256743391,985,1.950114e+06,1.332245e+07,1.332245e+07,96.97,92.040000,2026-06-27

In [81]:
query4 = pd.read_sql("SELECT avg(market_cap_rank) from crypto_record  WHERE total_volume > 1000000000 ", connection)
query4

   avg(market_cap_rank)
0            249.926829

In [83]:
query5 = pd.read_sql("SELECT * FROM crypto_record ORDER BY last_updated DESC LIMIT 1", connection)
query5

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,5668437.0,113683469483917,1,3.156319e+12,20048731.0,20048731.0,11187013.0,3993.42,2026-06-27

In [85]:
query6 = pd.read_sql("SELECT coin_id,MAX(price_inr) FROM coin_record where coin_id='bitcoin'",connection)
query6

   coin_id  MAX(price_inr)
0  bitcoin    1.107047e+07

In [86]:
query7 = pd.read_sql("SELECT *, avg(price_inr) FROM coin_record where coin_id = 'ethereum'",connection)
query7

    coin_id        date      price_inr  avg(price_inr)
0  ethereum  2025-06-28  207191.049691   266869.533047

In [87]:
query8 = pd.read_sql("SELECT * from coin_record where coin_id='bitcoin' and date between '2026-04-01' and '2026-04-30'",connection)
query8

    coin_id        date     price_inr
0   bitcoin  2026-04-01  6.378629e+06
1   bitcoin  2026-04-02  6.307964e+06
2   bitcoin  2026-04-03  6.219176e+06
3   bitcoin  2026-04-04  6.209570e+06
4   bitcoin  2026-04-05  6.257848e+06
5   bitcoin  2026-04-06  6.414171e+06
6   bitcoin  2026-04-07  6.401867e+06
7   bitcoin  2026-04-08  6.683689e+06
8   bitcoin  2026-04-09  6.562922e+06
9   bitcoin  2026-04-10  6.636645e+06
10  bitcoin  2026-04-11  6.794201e+06
11  bitcoin  2026-04-12  6.801701e+06
12  bitcoin  2026-04-13  6.685979e+06
13  bitcoin  2026-04-14  7.073662e+06
14  bitcoin  2026-04-15  6.911131e+06
15  bitcoin  2026-04-16  6.988481e+06
16  bitcoin  2026-04-17  6.992493e+06
17  bitcoin  2026-04-18  7.142283e+06
18  bitcoin  2026-04-19  7.012641e+06
19  bitcoin  2026-04-20  6.839334e+06
20  bitcoin  2026-04-21  7.065729e+06
21  bitcoin  2026-04-22  7.148144e+06
22  bitcoin  2026-04-23  7.334730e+06
23  bitcoin  2026-04-24  7.365353e+06
24  bitcoin  2026-04-25  7.284891e+06
25  bitcoin  2026-04-26  7.301369e+06
26  bitcoin  2026-04-27  7.412346e+06
27  bitcoin  2026-04-28  7.291979e+06
28  bitcoin  2026-04-29  7.225751e+06
29  bitcoin  2026-04-30  7.192314e+06

In [88]:
query9 = pd.read_sql("select coin_id, avg(price_inr) AS avg_price from coin_record GROUP BY coin_id ORDER BY avg(price_inr)DESC LIMIT 1",connection)
query9

   coin_id     avg_price
0  bitcoin  8.206198e+06

In [89]:
query10 = pd.read_sql("select ROUND(((select price_inr FROM coin_record WHERE coin_id='bitcoin' ORDER BY date DESC LIMIT 1) - (select price_inr FROM coin_record WHERE coin_id='bitcoin' ORDER BY date ASC LIMIT 1))*100.0 /(select price_inr FROM coin_record WHERE coin_id='bitcoin' ORDER BY date ASC LIMIT 1)) AS percentage_change",connection)
query10

   percentage_change
0              -38.0

In [90]:
query11 = pd.read_sql("select *,max(price_inr) as highest_price from oil_record where date BETWEEN '2021-06-10' AND '2026-06-10'",connection)
query11

         date  price_inr  highest_price
0  2022-03-08     123.64         123.64

In [91]:
query12= pd.read_sql("select strftime('%Y',date) AS Year,Avg(price_inr) AS Avg_price from oil_record group by strftime('%Y',date) order by Year,Avg_price",connection)
query12

    Year  Avg_price
0   1986  15.047689
1   1987  19.200512
2   1988  15.965409
3   1989  19.635486
4   1990  24.526576
5   1991  21.541367
6   1992  20.575564
7   1993  18.432200
8   1994  17.196429
9   1995  18.428805
10  1996  22.119173
11  1997  20.608254
12  1998  14.422072
13  1999  19.344980
14  2000  30.378520
15  2001  25.983120
16  2002  26.184960
17  2003  31.075240
18  2004  41.506024
19  2005  56.637251
20  2006  66.054659
21  2007  72.340595
22  2008  99.671502
23  2009  61.950437
24  2010  79.475714
25  2011  94.880873
26  2012  94.053333
27  2013  97.982540
28  2014  93.172222
29  2015  48.656706
30  2016  43.293651
31  2017  50.800320
32  2018  65.227470
33  2019  56.988320
34  2020  39.160437
35  2021  68.135100
36  2022  94.902869
37  2023  77.576532
38  2024  76.632240
39  2025  65.388105
40  2026  84.920342

In [92]:
query13 = pd.read_sql("select date,price_inr from oil_record where date BETWEEN '2020-03-01' AND '2020-04-30' order by date",connection)
query13

          date  price_inr
0   2020-03-02      46.78
1   2020-03-03      47.27
2   2020-03-04      46.78
3   2020-03-05      45.90
4   2020-03-06      41.14
5   2020-03-09      31.05
6   2020-03-10      34.47
7   2020-03-11      33.13
8   2020-03-12      31.56
9   2020-03-13      31.72
10  2020-03-16      28.96
11  2020-03-17      26.96
12  2020-03-18      20.48
13  2020-03-19      25.09
14  2020-03-20      19.48
15  2020-03-23      23.33
16  2020-03-24      21.03
17  2020-03-25      20.75
18  2020-03-26      16.60
19  2020-03-27      15.48
20  2020-03-30      14.10
21  2020-03-31      20.51
22  2020-04-01      20.28
23  2020-04-02      25.18
24  2020-04-03      28.36
25  2020-04-06      26.21
26  2020-04-07      23.54
27  2020-04-08      24.97
28  2020-04-09      22.90
29  2020-04-13      22.36
30  2020-04-14      20.15
31  2020-04-15      19.96
32  2020-04-16      19.82
33  2020-04-17      18.31
34  2020-04-20     -36.98
35  2020-04-21       8.91
36  2020-04-22      13.64
37  2020-04-23      15.06
38  2020-04-24      15.99
39  2020-04-27      12.17
40  2020-04-28      12.40
41  2020-04-29      15.04
42  2020-04-30      19.23

In [93]:
query14 = pd.read_sql("SELECT *,min(price_inr) as lowest_price FROM oil_record WHERE date BETWEEN '2016-06-10' AND '2026-06-10'",connection)
query14

         date  price_inr  lowest_price
0  2020-04-20     -36.98        -36.98

In [94]:
query15 = pd.read_sql("SELECT strftime('%Y',date) AS year, MAX(price_inr) as max_price, min(price_inr) as min_price, ROUND(MAX(price_inr)-min(price_inr),2) AS Volatility FROM oil_record GROUP BY strftime('%Y',date) ORDER BY year",connection)
query15

    year  max_price  min_price  Volatility
0   1986      26.53      10.25       16.28
1   1987      22.44      15.12        7.32
2   1988      18.54      12.58        5.96
3   1989      24.62      16.99        7.63
4   1990      41.07      15.43       25.64
5   1991      32.25      17.43       14.82
6   1992      23.03      17.89        5.14
7   1993      21.05      13.98        7.07
8   1994      20.72      13.89        6.83
9   1995      20.53      16.86        3.67
10  1996      26.55      17.33        9.22
11  1997      26.55      17.60        8.95
12  1998      17.93      10.82        7.11
13  1999      28.03      11.38       16.65
14  2000      37.22      23.91       13.31
15  2001      32.21      17.50       14.71
16  2002      32.68      18.02       14.66
17  2003      37.96      25.25       12.71
18  2004      56.37      32.49       23.88
19  2005      69.91      42.16       27.75
20  2006      77.05      55.90       21.15
21  2007      99.16      50.51       48.65
22  2008     145.31      30.28      115.03
23  2009      81.03      34.03       47.00
24  2010      91.48      64.78       26.70
25  2011     113.39      75.40       37.99
26  2012     109.39      77.72       31.67
27  2013     110.62      86.65       23.97
28  2014     107.95      53.45       54.50
29  2015      61.36      34.55       26.81
30  2016      54.01      26.19       27.82
31  2017      60.46      42.48       17.98
32  2018      77.41      44.48       32.93
33  2019      66.24      46.31       19.93
34  2020      63.27     -36.98      100.25
35  2021      85.64      47.47       38.17
36  2022     123.64      71.05       52.59
37  2023      93.67      66.61       27.06
38  2024      87.69      66.73       20.96
39  2025      80.73      55.44       25.29
40  2026     114.58      56.01       58.57

In [95]:
query16 = pd.read_sql("select close,high,low,Ticker from stocks_record order by Ticker",connection)
query16

             Close          High           Low Ticker
0              NaN           NaN           NaN  ^GSPC
1      3257.850098   3258.139893   3235.530029  ^GSPC
2      3234.850098   3246.149902   3222.340088  ^GSPC
3      3246.280029   3246.840088   3214.639893  ^GSPC
4      3237.179932   3244.909912   3232.429932  ^GSPC
...            ...           ...           ...    ...
4804  24865.699219  24989.349609  24603.500000  ^NSEI
4805           NaN           NaN           NaN  ^NSEI
4806  24480.500000  24602.449219  24305.400391  ^NSEI
4807  24765.900391  24854.199219  24529.400391  ^NSEI
4808  24450.449219  24700.900391  24415.750000  ^NSEI

[4809 rows x 4 columns]

In [98]:
query17 = pd.read_sql("select Ticker,max(close) from stocks_record where Ticker == '^IXIC'",connection)
query17

  Ticker    max(close)
0  ^IXIC  23958.470703

In [99]:
query18 =pd.read_sql("select date,high,low,(High-Low) as price_difference from stocks_record WHERE Ticker ='^GSPC' ORDER BY price_difference DESC LIMIT 5",connection)
query18

                  Date         High          Low  price_difference
0  2025-04-09 00:00:00  5481.339844  4948.430176        532.909668
1  2025-04-07 00:00:00  5246.569824  4835.040039        411.529785
2  2025-04-08 00:00:00  5267.470215  4910.419922        357.050293
3  2025-04-10 00:00:00  5353.149902  5115.270020        237.879883
4  2025-11-20 00:00:00  6770.350098  6534.049805        236.300293

In [100]:
query19 = pd.read_sql("select Ticker,strftime('%Y-%m',Date) AS Month, AVG(close) AS avg_close from stocks_record group by Ticker,strftime('%Y-%m',Date) Order by Ticker,Month",connection)
query19

    Ticker    Month     avg_close
0    ^GSPC  2020-01   3278.202858
1    ^GSPC  2020-02   3277.314183
2    ^GSPC  2020-03   2652.393632
3    ^GSPC  2020-04   2761.975226
4    ^GSPC  2020-05   2919.608484
..     ...      ...           ...
220  ^NSEI  2025-11  25894.834396
221  ^NSEI  2025-12  25997.738725
222  ^NSEI  2026-01  25652.962695
223  ^NSEI  2026-02  25625.575098
224  ^NSEI  2026-03  24640.637207

[225 rows x 3 columns]

In [101]:
query20 = pd.read_sql("""select Ticker,avg(volume) as Avg_NSEI from stocks_record where Ticker ='^NSEI' and Date between '2024-01-01' and '2024-12-31'""",connection)
query20

  Ticker       Avg_NSEI
0  ^NSEI  314049.795918

# Join Queries

In [102]:
pd.read_sql("select * from coin_record where coin_id ='bitcoin'",connection)

     coin_id        date     price_inr
0    bitcoin  2025-06-28  9.156218e+06
1    bitcoin  2025-06-29  9.177823e+06
2    bitcoin  2025-06-30  9.263092e+06
3    bitcoin  2025-07-01  9.181709e+06
4    bitcoin  2025-07-02  9.054321e+06
..       ...         ...           ...
361  bitcoin  2026-06-24  5.963458e+06
362  bitcoin  2026-06-25  5.752303e+06
363  bitcoin  2026-06-26  5.636909e+06
364  bitcoin  2026-06-27  5.657787e+06
365  bitcoin  2026-06-27  5.678251e+06

[366 rows x 3 columns]

In [103]:
query21 = pd.read_sql("SELECT(select Avg(price_inr) from coin_record WHERE strftime('%Y',date)='2025') AS Bitcoin_avg_price,(SELECT Avg(price_inr) from oil_record where strftime('%Y',date)='2025') AS Oil_avg_price",connection)
query21

   Bitcoin_avg_price  Oil_avg_price
0       3.255156e+06      65.388105

In [104]:
query22 = pd.read_sql("SELECT date(coin_record.date) AS Date,coin_record.price_inr AS Bitcoin_price,stocks_record.close AS GSPC_price FROM coin_record JOIN stocks_record ON date(coin_record.date) = date(stocks_record.date) WHERE coin_record.coin_id = 'bitcoin' AND stocks_record.Ticker ='^GSPC'",connection)
query22

           Date  Bitcoin_price   GSPC_price
0    2025-06-30   9.263092e+06  6204.950195
1    2025-07-01   9.181709e+06  6198.009766
2    2025-07-02   9.054321e+06  6227.419922
3    2025-07-03   9.325640e+06  6279.350098
4    2025-07-04   9.360532e+06          NaN
..          ...            ...          ...
174  2026-03-02   5.984275e+06  6881.620117
175  2026-03-03   6.305545e+06  6816.629883
176  2026-03-04   6.286193e+06  6869.500000
177  2026-03-05   6.694568e+06  6830.709961
178  2026-03-06   6.505413e+06  6740.020020

[179 rows x 3 columns]

In [105]:
query23 = pd.read_sql("SELECT(select Avg(price_inr) from coin_record WHERE coin_id ='ethereum' AND strftime('%Y',date)='2025') AS Bitcoin_avg_price,(SELECT Avg(price_inr) from oil_record where strftime('%Y',date)='2025') AS Oil_avg_price",connection)
query23

   Bitcoin_avg_price  Oil_avg_price
0      323290.397924      65.388105

In [106]:
query24 = pd.read_sql("select oil_record.date,oil_record.price_inr AS oil_price, coin_record.price_inr AS Bitcoin_price FROM oil_record JOIN coin_record ON date(oil_record.date) = date(coin_record.date) WHERE coin_record.coin_id = 'bitcoin' AND oil_record.price_inr > (SELECT AVG(price_inr) * 1.10 FROM oil_record) ORDER BY oil_record.date", connection)
query24

           date  oil_price  Bitcoin_price
0    2025-06-30      66.30   9.263092e+06
1    2025-07-01      66.64   9.181709e+06
2    2025-07-02      68.66   9.054321e+06
3    2025-07-03      68.13   9.325640e+06
4    2025-07-07      69.16   9.337524e+06
..          ...        ...            ...
239  2026-06-15      84.65   6.250059e+06
240  2026-06-16      79.80   6.281483e+06
241  2026-06-17      80.65   6.204054e+06
242  2026-06-18      80.35   6.111071e+06
243  2026-06-22      78.94   5.964697e+06

[244 rows x 3 columns]

In [107]:
query25 = pd.read_sql("SELECT date(coin_record.date) AS Date, coin_record.coin_id AS coin_name,stocks_record.close AS NSEI_price FROM coin_record JOIN stocks_record ON date(coin_record.date) = date(stocks_record.date) WHERE stocks_record.Ticker = '^NSEI' ORDER BY date, coin_id",connection)
query25

           Date coin_name    NSEI_price
0    2025-06-30   bitcoin  25517.050781
1    2025-06-30  ethereum  25517.050781
2    2025-06-30    tether  25517.050781
3    2025-07-01   bitcoin  25541.800781
4    2025-07-01  ethereum  25541.800781
..          ...       ...           ...
532  2026-03-05  ethereum  24765.900391
533  2026-03-05    tether  24765.900391
534  2026-03-06   bitcoin  24450.449219
535  2026-03-06  ethereum  24450.449219
536  2026-03-06    tether  24450.449219

[537 rows x 3 columns]

In [108]:
query26 = pd.read_sql("""SELECT oil_record.date AS Date,stocks_record.close AS "^GSPC_Stock_price" ,oil_record.price_inr AS oil_price FROM stocks_record JOIN oil_record ON date(stocks_record.date) = date(oil_record.date) WHERE Ticker ='^GSPC' AND date(stocks_record.date) = '2025-01-02'""", connection)
query26

         Date  ^GSPC_Stock_price  oil_price
0  2025-01-02        5868.549805      73.79

In [109]:
query27 =pd.read_sql("""SELECT oil_record.date AS Date,coin_record.price_inr AS Bitcoin_price,oil_record.price_inr AS oil_price FROM coin_record JOIN oil_record ON date(coin_record.date) = date(oil_record.date) WHERE coin_id ='bitcoin' AND date(oil_record.date) ='2025-07-25'""", connection)
query27

         Date  Bitcoin_price  oil_price
0  2025-07-25   1.022943e+07      66.38

In [110]:
query28 =pd.read_sql("""SELECT stocks_record.date,stocks_record.close AS "^IXIC_Stock_price" ,coin_record.price_inr AS Ethereum_price FROM stocks_record JOIN coin_record ON date(stocks_record.date) = date(coin_record.date) WHERE Ticker ='^IXIC' ORDER BY stocks_record.date""", connection)
query28

                    Date  ^IXIC_Stock_price  Ethereum_price
0    2025-06-30 00:00:00       20369.730469    9.263092e+06
1    2025-06-30 00:00:00       20369.730469    2.138668e+05
2    2025-06-30 00:00:00       20369.730469    8.546600e+01
3    2025-07-01 00:00:00       20202.890625    9.181709e+06
4    2025-07-01 00:00:00       20202.890625    2.132479e+05
..                   ...                ...             ...
532  2026-03-05 00:00:00       22748.990234    1.958386e+05
533  2026-03-05 00:00:00       22748.990234    9.213504e+01
534  2026-03-06 00:00:00       22387.679688    6.505413e+06
535  2026-03-06 00:00:00       22387.679688    1.904145e+05
536  2026-03-06 00:00:00       22387.679688    9.179148e+01

[537 rows x 3 columns]

In [111]:
query29 =pd.read_sql("""SELECT stocks_record.date as Date,stocks_record.Ticker,stocks_record.close AS stock_price,coin_record.coin_id,coin_record.price_inr AS Coin_price FROM stocks_record JOIN coin_record ON date(stocks_record.Date) = date(coin_record.Date) WHERE strftime('%Y',coin_record.date)='2025' ORDER BY date, coin_id,Ticker""",connection)
query29

                     Date Ticker   stock_price   coin_id    Coin_price
0     2025-06-30 00:00:00  ^GSPC   6204.950195   bitcoin  9.263092e+06
1     2025-06-30 00:00:00  ^IXIC  20369.730469   bitcoin  9.263092e+06
2     2025-06-30 00:00:00  ^NSEI  25517.050781   bitcoin  9.263092e+06
3     2025-06-30 00:00:00  ^GSPC   6204.950195  ethereum  2.138668e+05
4     2025-06-30 00:00:00  ^IXIC  20369.730469  ethereum  2.138668e+05
...                   ...    ...           ...       ...           ...
1183  2025-12-31 00:00:00  ^IXIC  23241.990234  ethereum  2.666209e+05
1184  2025-12-31 00:00:00  ^NSEI  26129.599609  ethereum  2.666209e+05
1185  2025-12-31 00:00:00  ^GSPC   6845.500000    tether  8.968155e+01
1186  2025-12-31 00:00:00  ^IXIC  23241.990234    tether  8.968155e+01
1187  2025-12-31 00:00:00  ^NSEI  26129.599609    tether  8.968155e+01

[1188 rows x 5 columns]

In [112]:
import pandas as pd
query30 = pd.read_sql("""SELECT stocks_record.date,stocks_record.Ticker,stocks_record.close AS Stock_price,coin_record.price_inr AS Bitcoin_price,oil_record.price_inr AS Oil_price FROM stocks_record JOIN oil_record on date(stocks_record.date) = date(oil_record.date) JOIN coin_record on date(stocks_record.date) = date(coin_record.date) WHERE coin_record.coin_id ='bitcoin' ORDER BY stocks_record.date, stocks_record.Ticker""", connection)
query30

                    Date Ticker   Stock_price  Bitcoin_price  Oil_price
0    2025-06-30 00:00:00  ^GSPC   6204.950195   9.263092e+06      66.30
1    2025-06-30 00:00:00  ^IXIC  20369.730469   9.263092e+06      66.30
2    2025-06-30 00:00:00  ^NSEI  25517.050781   9.263092e+06      66.30
3    2025-07-01 00:00:00  ^GSPC   6198.009766   9.181709e+06      66.64
4    2025-07-01 00:00:00  ^IXIC  20202.890625   9.181709e+06      66.64
..                   ...    ...           ...            ...        ...
508  2026-03-05 00:00:00  ^IXIC  22748.990234   6.694568e+06      80.88
509  2026-03-05 00:00:00  ^NSEI  24765.900391   6.694568e+06      80.88
510  2026-03-06 00:00:00  ^GSPC   6740.020020   6.505413e+06      90.77
511  2026-03-06 00:00:00  ^IXIC  22387.679688   6.505413e+06      90.77
512  2026-03-06 00:00:00  ^NSEI  24450.449219   6.505413e+06      90.77

[513 rows x 5 columns]

#**Streamlit**

---

In [113]:
!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

--2026-06-27 05:56:56--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2026.6.1/cloudflared-linux-amd64 [following]
--2026-06-27 05:56:56--  https://github.com/cloudflare/cloudflared/releases/download/2026.6.1/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/74ac6867-a1bf-4352-b955-c16fbb86d0f6?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-06-27T06%3A46%3A56Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-06-27T05%3A46%3A33Z&ske=2026-06-27T06%3A46%3A56Z&sks=b&skv=2018-11-09&sig=vxOimbi%2Boij4omm897ZMQ3RfjI9QHov2QYKamj%2BXSsE%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc4MjU0MTUxOSwibmJmIjoxNzgyNTM5NzE5LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.-8xwphZqjtVrDrskFKyr2wOeelBoLsJJ3rQOfVyaNr4&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream [following]
--2026-06-27 05:56:56--  https://release-assets.githubusercontent.com/github-production-release-asset/106867604/74ac6867-a1bf-4352-b955-c16fbb86d0f6?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-06-27T06%3A46%3A56Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-06-27T05%3A46%3A33Z&ske=2026-06-27T06%3A46%3A56Z&sks=b&skv=2018-11-09&sig=vxOimbi%2Boij4omm897ZMQ3RfjI9QHov2QYKamj%2BXSsE%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc4MjU0MTUxOSwibmJmIjoxNzgyNTM5NzE5LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.-8xwphZqjtVrDrskFKyr2wOeelBoLsJJ3rQOfVyaNr4&response-content-disposition=attachment%3B%20filename%3Dcloudflared-linux-amd64&response-content-type=application%2Foctet-stream
Resolving release-assets.githubusercontent.com (release-assets.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to release-assets.githubusercontent.com (release-assets.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39244939 (37M) [application/octet-stream]
Saving to: ‘cloudflared-linux-amd64.1’

cloudflared-linux-a 100%[===================>]  37.43M   200MB/s    in 0.2s

2026-06-27 05:56:56 (200 MB/s) - ‘cloudflared-linux-amd64.1’ saved [39244939/39244939]

nohup: appending output to 'nohup.out'

In [114]:
!pip install streamlit-option-menu

Requirement already satisfied: streamlit-option-menu in /usr/local/lib/python3.12/dist-packages (0.4.0)
Requirement already satisfied: streamlit>=1.36 in /usr/local/lib/python3.12/dist-packages (from streamlit-option-menu) (1.58.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (8.4.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit>=1.36->streamlit-option-menu) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2.22.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit>=1.36->streamlit-option-menu) (3.18)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2026.5.20)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit>=1.36->streamlit-option-menu) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit>=1.36->streamlit-option-menu) (2026.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (1.17.0)

In [118]:
%%writefile app.py

import streamlit as st
import sqlite3
import pandas as pd

connection = sqlite3.connect("crypto.db")
cursor = connection.cursor()

from streamlit_option_menu import option_menu

with st.sidebar:
    selected = option_menu("CONTENTS", ["📋Cross Market Overview", '📝SQL Query','💰Top 3 Crypto Analysis'], menu_icon="cast", default_index=1)
if selected  == "📋Cross Market Overview":
        st.title("**📊Cross-Market Analysis**")
        st.divider()
        st.caption("crytpto oil stock Market powered analytics")

        col1 , col2 =st.columns(2)
        with col1:
          start_date = st.date_input("start Date")
        with col2:
          end_date = st.date_input("End Date")

        bitcoin_avg = pd.read_sql("select avg(price_inr) as Bitcoin_avg from coin_record where coin_id = 'bitcoin' and date between ? and ?",connection,params =[str(start_date),str(end_date)])
        value = bitcoin_avg.iloc[0,0]
        oil_avg = pd.read_sql("select avg(price_inr) as oil_avg from oil_record where date between ? and ?",connection,params =[str(start_date),str(end_date)])
        value1 = oil_avg.iloc[0,0]
        sp500_avg = pd.read_sql("select avg(close) as sp500_avg from stocks_record where Ticker = '^GSPC' and date between ? and ?",connection,params =[str(start_date),str(end_date)])
        value2 = sp500_avg.iloc[0,0]
        nifty_avg = pd.read_sql("select avg(close) as nifty_avg from stocks_record where Ticker = '^NSEI' and date between ? and ?",connection,params =[str(start_date),str(end_date)])
        value3 = nifty_avg.iloc[0,0]

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Bitcoin Avg($)",value)
        col2.metric("Oil Avg($)",value1)
        col3.metric("SP500 Avg($)",value2)
        col4.metric("Nifty Avg($)",value3)

        st.header("📈**Daily Market Snapshot**")

        start_date =str(start_date)
        end_date = str(end_date)

        bitcoin = pd.read_sql("""SELECT date(date)as date,price_inr AS bitcoin_price from coin_record WHERE coin_id='bitcoin'and date BETWEEN ? and ?""",connection,params=(start_date,end_date))
        oil = pd.read_sql("""select date(date) as date,price_inr as oil_price from oil_record where date between ? and ?""",connection,params=(start_date,end_date))
        sp500 = pd.read_sql("""select date(Date) as date,close as sp500 from stocks_record where Ticker ='^GSPC'AND date(Date) between ? and ?""",connection,params=(start_date,end_date))
        nifty = pd.read_sql("""select date(Date) as date,close as nifty from stocks_record where Ticker='^NSEI'and date(Date) between ? and ?""",connection,params=(start_date,end_date))

        snapshot = bitcoin.merge(oil, on="date")
        snapshot = snapshot.merge(sp500, on="date")
        snapshot = snapshot.merge(nifty, on="date")

        st.dataframe(snapshot)

if selected  == "📝SQL Query":
      option = st.selectbox(
    "Choose a query:",
    ("1.Find the top 3 cryptocurrencies by market cap.",
     "2.List all coins where circulating supply exceeds 90% of total supply.",
     "3.Get coins that are within 10% of their all-time-high (ATH).",
     "4.Find the average market cap rank of coins with volume above $1B.",
     "5.Get the most recently updated coin.",
     "6.Find the highest daily price of Bitcoin in the last 365 days.",
    "7.Calculate the average daily price of Ethereum in the past 1 year.",
    "8.Show the daily price trend of Bitcoin in January 2025.",
    "9.Find the coin with the highest average price over 1 year.",
    "10.Get the % change in Bitcoin’s price between Sep 2024 and Sep 2025.",
    "11.Find the highest oil price in the last 5 years.",
    "12.Get the average oil price per year.",
    "13.Show oil prices during COVID crash (March–April 2020).",
    "14.Find the lowest price of oil in the last 10 years.",
    "15.Calculate the volatility of oil prices (max-min difference per year).",
    "16.Get all stock prices for a given ticker.",
    "17.Find the highest closing price for NASDAQ (^IXIC).",
    "18.List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC).",
    "19.Get monthly average closing price for each ticker.",
    "20.Get average trading volume of NSEI in 2024.",
    "21.Compare Bitcoin vs Oil average price in 2025.",
    "22.Check if Bitcoin moves with S&P 500 (correlation idea).",
    "23.Compare Ethereum and NASDAQ daily prices for 2025.",
    "24.Find days when oil price spiked and compare with Bitcoin price change.",
    "25.Compare top 3 coins daily price trend vs Nifty (^NSEI).",
    "26.Compare stock prices (^GSPC) with crude oil prices on the same dates.",
    "27.Correlate Bitcoin closing price with crude oil closing price (same date).",
    "28.Compare NASDAQ (^IXIC) with Ethereum price trends.",
    "29.Join top 3 crypto coins with stock indices for 2025.",
    "30.Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison."))

      if st.button("Run Query"):

        if option == "1.Find the top 3 cryptocurrencies by market cap.":
          df = pd.read_sql("SELECT * FROM crypto_record ORDER BY market_cap DESC limit 3",connection)
          st.write(df)

        if option == "2.List all coins where circulating supply exceeds 90% of total supply.":
          df = pd.read_sql("SELECT * FROM crypto_record WHERE circulating_supply > 0.9 * total_supply",connection )
          st.write(df)

        if option == "3.Get coins that are within 10% of their all-time-high (ATH).":
          df = pd.read_sql("select * FROM crypto_record WHERE current_price >= ath * 0.90",connection)
          st.write(df)

        if option == "4.Find the average market cap rank of coins with volume above $1B.":
          df = pd.read_sql("SELECT avg(market_cap_rank) from crypto_record  WHERE total_volume > 1000000000 ", connection)
          st.write(df)

        if option == "5.Get the most recently updated coin.":
          df = pd.read_sql("SELECT * FROM crypto_record ORDER BY last_updated DESC LIMIT 1", connection)
          st.write(df)

        if option == "6.Find the highest daily price of Bitcoin in the last 365 days.":
          df = pd.read_sql("SELECT *,MAX(price_inr) FROM coin_record where coin_id='bitcoin'",connection)
          st.write(df)

        if option == "7.Calculate the average daily price of Ethereum in the past 1 year.":
          df = pd.read_sql("SELECT *, avg(price_inr) FROM coin_record where coin_id = 'ethereum'",connection)
          st.write(df)

        if option == "8.Show the daily price trend of Bitcoin in January 2025.":
          df = pd.read_sql("SELECT * from coin_record where coin_id='bitcoin' and date between '2026-04-01' and '2026-04-30'",connection)
          st.write(df)

        if option == "9.Find the coin with the highest average price over 1 year.":
          df = pd.read_sql("select coin_id, avg(price_inr) AS avg_price from coin_record GROUP BY coin_id ORDER BY avg(price_inr)DESC LIMIT 1",connection)
          st.write(df)

        if option == "10.Get the % change in Bitcoin’s price between Sep 2024 and Sep 2025.":
          df = pd.read_sql("select ROUND(((select price_inr FROM coin_record WHERE coin_id='bitcoin' ORDER BY date DESC LIMIT 1) - (select price_inr FROM coin_record WHERE coin_id='bitcoin' ORDER BY date ASC LIMIT 1))*100.0 /(select price_inr FROM coin_record WHERE coin_id='bitcoin' ORDER BY date ASC LIMIT 1)) AS percentage_change",connection)
          st.write(df)

        if option == "11.Find the highest oil price in the last 5 years.":
          df = pd.read_sql("select *,max(price_inr) as highest_price from oil_record where date BETWEEN '2021-06-10' AND '2026-06-10'",connection)
          st.write(df)

        if option == "12.Get the average oil price per year.":
          df = pd.read_sql("select strftime('%Y',date) AS Year,Avg(price_inr) AS Avg_price from oil_record group by strftime('%Y',date) order by Year,Avg_price",connection)
          st.write(df)

        if option == "13.Show oil prices during COVID crash (March–April 2020).":
          df = pd.read_sql("select date,price_inr from oil_record where date BETWEEN '2020-03-01' AND '2020-04-30' order by date",connection)
          st.write(df)

        if option == "14.Find the lowest price of oil in the last 10 years.":
          df = pd.read_sql("SELECT *,min(price_inr) as lowest_price FROM oil_record WHERE date BETWEEN '2016-06-10' AND '2026-06-10'",connection)
          st.write(df)

        if option == "15.Calculate the volatility of oil prices (max-min difference per year).":
          df = pd.read_sql("SELECT strftime('%Y',date) AS year, MAX(price_inr) as max_price, min(price_inr) as min_price, ROUND(MAX(price_inr)-min(price_inr),2) AS Volatility FROM oil_record GROUP BY strftime('%Y',date) ORDER BY year",connection)
          st.write(df)

        if option == "16.Get all stock prices for a given ticker.":
          df = pd.read_sql("select close,high,low,Ticker from stocks_record order by Ticker",connection)
          st.write(df)

        if option == "17.Find the highest closing price for NASDAQ (^IXIC).":
          df = pd.read_sql("select max(close) from stocks_record where Ticker == '^IXIC'",connection)
          st.write(df)

        if option == "18.List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC).":
          df = pd.read_sql("select date,high,low,(High-Low) as price_difference from stocks_record WHERE Ticker ='^GSPC' ORDER BY price_difference DESC LIMIT 5",connection)
          st.write(df)

        if option == "19.Get monthly average closing price for each ticker.":
          df = pd.read_sql("select Ticker,strftime('%Y-%m',Date) AS Month, AVG(close) AS avg_close from stocks_record group by Ticker,strftime('%Y-%m',Date) Order by Ticker,Month",connection)
          st.write(df)

        if option == "20.Get average trading volume of NSEI in 2024.":
          df = pd.read_sql("""select avg(volume) as Avg_NSEI from stocks_record where Ticker ='^NSEI' and Date between '2024-01-01' and '2024-12-31'""",connection)
          st.write(df)

        if option == "21.Compare Bitcoin vs Oil average price in 2025.":
          df = pd.read_sql("SELECT(select Avg(price_inr) from coin_record WHERE strftime('%Y',date)='2025') AS Bitcoin_avg_price,(SELECT Avg(price_inr) from oil_record where strftime('%Y',date)='2025') AS Oil_avg_price",connection)
          st.write(df)

        if option == "22.Check if Bitcoin moves with S&P 500 (correlation idea).":
          df = pd.read_sql("SELECT date(coin_record.date) AS Date,coin_record.price_inr AS Bitcoin_price,stocks_record.close AS GSPC_price FROM coin_record JOIN stocks_record ON date(coin_record.date) = date(stocks_record.date) WHERE coin_record.coin_id = 'bitcoin' AND stocks_record.Ticker ='^GSPC'",connection)
          st.write(df)

        if option == "23.Compare Ethereum and NASDAQ daily prices for 2025.":
          df = pd.read_sql("SELECT(select Avg(price_inr) from coin_record WHERE coin_id ='ethereum' AND strftime('%Y',date)='2025') AS Bitcoin_avg_price,(SELECT Avg(price_inr) from oil_record where strftime('%Y',date)='2025') AS Oil_avg_price",connection)
          st.write(df)

        if option == "24.Find days when oil price spiked and compare with Bitcoin price change.":
          df = pd.read_sql("select oil_record.date,oil_record.price_inr AS oil_price, coin_record.price_inr AS Bitcoin_price FROM oil_record JOIN coin_record ON date(oil_record.date) = date(coin_record.date) WHERE coin_record.coin_id = 'bitcoin' AND oil_record.price_inr > (SELECT AVG(price_inr) * 1.10 FROM oil_record) ORDER BY oil_record.date", connection)
          st.write(df)

        if option == "25.Compare top 3 coins daily price trend vs Nifty (^NSEI).":
          df = pd.read_sql("SELECT date(coin_record.date) AS Date, coin_record.coin_id AS coin_name,stocks_record.close AS NSEI_price FROM coin_record JOIN stocks_record ON date(coin_record.date) = date(stocks_record.date) WHERE stocks_record.Ticker = '^NSEI' ORDER BY date, coin_id",connection)
          st.write(df)

        if option == "26.Compare stock prices (^GSPC) with crude oil prices.":
          df = pd.read_sql("""SELECT oil_record.date AS Date,stocks_record.close AS "^GSPC_Stock_price" ,oil_record.price_inr AS oil_price FROM stocks_record JOIN oil_record ON date(stocks_record.date) = date(oil_record.date) WHERE Ticker ='^GSPC' AND date(stocks_record.date) = '2025-01-02'""", connection)
          st.write(df)

        if option == "27.Correlate Bitcoin closing price with crude oil closing price.":
          df =pd.read_sql("""SELECT oil_record.date AS Date,coin_record.price_inr AS Bitcoin_price,oil_record.price_inr AS oil_price FROM coin_record JOIN oil_record ON date(coin_record.date) = date(oil_record.date) WHERE coin_id ='bitcoin' AND date(oil_record.date) ='2025-07-25'""", connection)
          st.write(df)

        if option == "28.Compare NASDAQ (^IXIC) with Ethereum price trends.":
          df= pd.read_sql("""SELECT stocks_record.date,stocks_record.close AS "^IXIC_Stock_price" ,coin_record.price_inr AS Ethereum_price FROM stocks_record JOIN coin_record ON date(stocks_record.date) = date(coin_record.date) WHERE Ticker ='^IXIC' ORDER BY stocks_record.date""", connection)
          st.write(df)

        if option == "29.Join top 3 crypto coins with stock indices for 2025.":
          df =pd.read_sql("""SELECT stocks_record.date as Date,stocks_record.Ticker,stocks_record.close AS stock_price,coin_record.coin_id,coin_record.price_inr AS Coin_price FROM stocks_record JOIN coin_record ON date(stocks_record.Date) = date(coin_record.Date) WHERE strftime('%Y',coin_record.date)='2025' ORDER BY date, coin_id,Ticker""",connection)
          st.write(df)

        if option == "30.Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison.":
          df=pd.read_sql("""SELECT stocks_record.date,stocks_record.Ticker,stocks_record.close AS Stock_price,coin_record.price_inr AS Bitcoin_price,oil_record.price_inr AS Oil_price FROM stocks_record JOIN oil_record on date(stocks_record.date) = date(oil_record.date) JOIN coin_record on date(stocks_record.date) = date(coin_record.date) WHERE coin_record.coin_id ='bitcoin' ORDER BY stocks_record.date, stocks_record.Ticker""", connection)
          st.write(df)

if selected  == "💰Top 3 Crypto Analysis":
        st.title("🪙Top 3 Crypto Analysis")
        top3 = pd.read_sql("select coin_id from coin_record",connection)
        coin = st.selectbox("Select Cryptocurrency",["Bitcoin","Ethereum","Tether"])

        start_date =st.date_input("Start Date")
        end_date =st.date_input("End Date")

        if coin == "Bitcoin":
          df = pd.read_sql("select date, price_inr FROM coin_record WHERE coin_id ='bitcoin' AND date between ? and ? order by date",connection,params=(start_date,end_date))

        if coin =="Ethereum":
          df = pd.read_sql("select date, price_inr FROM coin_record WHERE coin_id ='ethereum' AND date between ? and ? order by date",connection,params=(start_date,end_date))

        if coin =="Tether":
          df = pd.read_sql("select date, price_inr FROM coin_record WHERE coin_id ='tether' AND date between ? and ? order by date",connection,params=(start_date,end_date))


        st.subheader("📈Daily Price Table")
        st.dataframe(df,use_container_width=True)

Overwriting app.py

In [119]:
!streamlit run /content/app.py &>/content/logs.txt &

In [117]:
!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

Your tunnel url https://funny-pressed-accomplished-muslim.trycloudflare.com